### ISSUE TITLE
宽屏界面下如何使登录界面适应宽屏?

### ISSUE THREAD

**Issue by pwnhub1024** [SleepNap/BeiDou#20]
希望可以告知对应的wz节点

**Comment by leevccc** [comment]
如果你自己修改了大边框的话可以尝试这三个配置值
EzorsiaV2WzIncluded=false

CustomLoginFrame=true

bigLoginFrame=true

**Comment by pwnhub1024** [comment]
您好，很感谢您的回复。
我尝试了以下操作：
修改EzorsiaV2WzIncluded.wz中的1920x768的frame图片
修改Map.wz->back->login->11的图片
但为何最终的效果的上半部分会有割裂？
<a href="https://img.vinua.cn/image/Snipaste-2024-07-28-20-53-29.IjChR"><img src="https://img.vinua.cn/images/IjChR.png" alt="Snipaste 2024 07 28 20 53 29" border="0"></a>

**Comment by yainse** [comment]
> 您好，很感谢您的回复。 我尝试了以下操作： 修改EzorsiaV2WzIncluded.wz中的1920x768的frame图片 修改Map.wz->back->login->11的图片 但为何最终的效果的上半部分会有割裂？ [![Snipaste 2024 07 28 20 53 29](https://camo.githubusercontent.com/c5a67cb112ba76fd041e746d985e5ac5b84c6221d24ab230016a91fb0fe73b72/68747470733a2f2f696d672e76696e75612e636e2f696d616765732f496a4368522e706e67)](https://img.vinua.cn/image/Snipaste-2024-07-28-20-53-29.IjChR)

如果你需要对高分辨进行适配，还需要对wz对应资源的坐标进行修改。 不然就会出现图中的问题。
