### ISSUE TITLE
【优化】web端发放装备一类的道具，只能单个发放，超过数量1会后端抛异常

### ISSUE THREAD

**Issue by jarecl** [SleepNap/BeiDou#35]
个人想法：
方案一：实现装备的批量发放，一次能到包里很多个
方案二：try catch里面自己拦截这个特定异常做处理，让前端直接返回特定提示【装备类只能一件一件发放，不支持批量】

报错截图：
![image](https://github.com/user-attachments/assets/58a711fa-923d-4638-9085-6ba98f35e24f)

![image](https://github.com/user-attachments/assets/726c3314-9a3d-4720-a364-c1618e750174)

**Comment by SleepNap** [comment]
装备只能一件件发放，不修改，提示可以优化

**Comment by SleepNap** [comment]
已优化发放装备和发放物品提示，增加了限制不允许混发
